server:
  port: 9091
spring:
  application:
    name: account-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/account-test-db
    username: billing-account
    password: billing123$$
    driver-class-name: com.mysql.cj.jdbc.Driver
#eureka:
#  instance:
#    hostname: 65.2.110.100
#  client:
#    serviceUrl:
#      defaultZone: http://65.1.222.21:8761/eureka/
billing:
  app: This is billing App Default Account Service
  test: new Properties