server:
  port: 9091
spring:
  application:
    name: account-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/accountdb
    username: billing-account
    password: billing123$$
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    hostname: 65.1.222.20
  client:
    serviceUrl:
      defaultZone: http://65.1.222.21:8761/eureka/
billing:
  app: This is billing App Account Service
  test: new Properties
default:
  role: ROLE_DEFAULT
user:
  firstname:
    empty: First Name cannot be empty.
jwt:
  secretkey: secrete
  access-token-expiration: 5000000
  refresh-token-expiration: 10000000