server:
  port: 8765
spring:
  application:
    name: api-gateway
billing:
  app: This is billing App API Gateway default
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka