server:
  port: 8081
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
eureka:
  instance:
    hostname: 65.1.186.30
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
billing:
  app: This is billing App API-Gatway default