server:
  port: 8081
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
billing:
  app: This is billing App API-Gatway dev