server:
  port: 9099
spring:
  application:
    name: report-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
billing:
  app: This is billing App Reporting Service default