server:
  port: 9094
spring:
  application:
    name: reporting-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
billing:
  app: This is billing App Reporting Service default