#spring.application.name=service-registry
#server.port=8761
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
server:
  port: 8761
spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: 65.1.222.21
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
billing:
  app: This is billing App Registry Service default